package TextEditor;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andreas
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    private TextTab openNewTab()
    {
        TextTab tt = new TextTab("Tab " + (tabs.size() + 1));
        jTabbedPane1.add(tt);
        tabs.add(tt);
        return tt;
    }
    
    private TextTab openNewTabWithTextAndName(String text, String name)
    {
        TextTab tt = new TextTab(name);
        jTabbedPane1.add(tt);
        tabs.add(tt);
        tt.addText(text);
        return tt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Item_Open = new javax.swing.JMenuItem();
        Item_Save = new javax.swing.JMenuItem();
        Item_NewTab = new javax.swing.JMenuItem();
        Item_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        fileChooser.setDialogTitle("This is my open dialog");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jMenu1.setText("File");

        Item_Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Item_Open.setText("Open");
        Item_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_OpenActionPerformed(evt);
            }
        });
        jMenu1.add(Item_Open);

        Item_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Item_Save.setText("Save");
        Item_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_SaveActionPerformed(evt);
            }
        });
        jMenu1.add(Item_Save);

        Item_NewTab.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        Item_NewTab.setText("New Tab");
        Item_NewTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_NewTabActionPerformed(evt);
            }
        });
        jMenu1.add(Item_NewTab);

        Item_Exit.setText("Exit");
        Item_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Item_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_OpenActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
            File file = fileChooser.getSelectedFile();
            try
            {
                System.out.println(file.getName());
                String result = SaveLoad.loadFile(file.getAbsolutePath());
                TextTab tt = openNewTabWithTextAndName(result, file.getName());
            }
            catch(Exception ex)
            {
                System.out.println("ERROR OPENING FILE");
            }
        }
    }//GEN-LAST:event_Item_OpenActionPerformed

    private void Item_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item_ExitActionPerformed

    private void Item_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item_SaveActionPerformed

    private void Item_NewTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_NewTabActionPerformed
        openNewTab();
    }//GEN-LAST:event_Item_NewTabActionPerformed



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Item_Exit;
    private javax.swing.JMenuItem Item_NewTab;
    private javax.swing.JMenuItem Item_Open;
    private javax.swing.JMenuItem Item_Save;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    //Own Variables
    private List<JPanel> tabs = new ArrayList<JPanel>(Arrays.asList(jPanel1));
}


